FROM node:18

WORKDIR /app

COPY . .

RUN npm install

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    vim \
    git \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

CMD ["npm", "start"]
