FROM python:3.9-slim

RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app
RUN chown appuser:appuser /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY apparmor-test.py .
RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 5000

CMD ["python", "apparmor-test.py"]
